services:
  - name: fastapi
    type: container
    build:
      repo: https://github.com/huma-engineering/craft-cloud-examples
      branch: main
      dockerfile: Dockerfile
      context: .
    ingress:
      port: 8000
