services:
  - name: temporal-mosi
    type: temporal

  - name: temporal-tester-worker
    type: container
    build:
      repo: https://github.com/huma-engineering/craft-cloud-examples
      branch: main
      dockerfile: Dockerfile
      context: temporal
    command:
      start: "worker"
    envs:
      - type: configmap
        service: temporal-mosi
        name: temporal-info

  - name: temporal-tester-starter
    type: container
    build:
      repo: https://github.com/huma-engineering/craft-cloud-examples
      branch: main
      dockerfile: Dockerfile
      context: temporal
    schedule: "*/2 * * * *"
    command:
      start: "starter"
    envs:
      - type: configmap
        service: temporal-mosi
        name: temporal-info
