services:
  - name: temporal-mosi
    type: temporal

  - name: temporal-tester-worker
    type: container
    build:
      repo: https://github.com/huma-engineering/craft-cloud-examples
      branch: main
      dockerfile: temporal/Dockerfile
      context: temporal
    command:
      start: "python /app/app.py worker"
    envs:
      - type: configmap
        service: temporal-mosi
        name: temporal-info
        mapping: { address: TEMPORAL_ADDRESS }

  - name: temporal-tester-starter
    type: container
    build:
      repo: https://github.com/huma-engineering/craft-cloud-examples
      branch: main
      dockerfile: temporal/Dockerfile
      context: temporal
    schedule: "*/2 * * * *"
    command:
      start: "python /app/app.py starter"
    envs:
      - type: configmap
        service: temporal-mosi
        name: temporal-info
        mapping: { address: TEMPORAL_ADDRESS }
